### ISSUE TITLE
Problems on RadixLedger - Still Error

### ISSUE THREAD

**Issue by agung2019** [radixdlt/radixdlt-java#111]
There is a Bugs on RadixLedger as follow:

public <T extends Atom> Observable<T> getAllAtoms(EUID destination, Class<T> atomClass) {
		Objects.requireNonNull(destination);
		Objects.requireNonNull(atomClass);

		final AtomQuery<T> atomQuery = new AtomQuery<>(destination, atomClass);
		return radixNetwork.getRadixClients(destination.getShard())
			.flatMapObservable(client -> client.getAtoms(atomQuery))
			.doOnError(Throwable::printStackTrace)
			.retryWhen(new IncreasingRetryTimer())
			.filter(new Predicate<T>() {
				private final Set<RadixHash> atomsSeen = new HashSet<>();

line 86  .flatMapObservable(client -> client.getAtoms(atomQuery))

Please help and thanks
Agung

**Comment by laszlourszuly** [comment]
Hello Agung! Thank you for submitting a ticket!
Could you please elaborate a bit on exactly what's going wrong? Maybe with a small code snippet triggering the issue?

**Comment by agung2019** [comment]
Hai Las,

I think the issues on RadixLedger.java was closed since I download the
latest version of radix-java last night. I saw so many differrence or new
things on that source.

I am learning Radix code and I think the concept is very interesting but
somehow the "term of used" in the code was confusing something like Atom,
Particles, Universe and Token? So I am just guessing the translation of
term based on my opinion as follow (CMIIW)
- Atom = Coins
- Particle = Transaction
- Universe = Platform
- Token = Atom?

Anyway many thanks for your kindly attention.

Regards,
Agung





On 15 Nov 2018 9:01 pm, "László Urszuly" <notifications@github.com> wrote:

Hello Agung! Thank you for submitting a ticket!
Could you please elaborate a bit on exactly what's going wrong? Maybe with
a small code snippet triggering the issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/radixdlt/radixdlt-java/issues/111#issuecomment-439049444>,
or mute the thread

**Comment by nadam** [comment]
The terms are explained in the white paper.
https://papers.radixdlt.com/tempo/latest

**Comment by laszlourszuly** [comment]
As @nadam points out, the white paper may shed some light (https://docs.radixdlt.com/alpha/learn/whitepapers). There is also some material on Youtube you could look into (https://www.youtube.com/channel/UCWz_uLkOCrmSUnLAxSY4N5Q). Or perhaps our Knowledge Base (https://docs.radixdlt.com/alpha/)?

It's still a bit unclear to me, though, if there is an actual crash or misbehaviour we should take a closer look at?

If you think something is broken; could you please:

1. State the version of the Radix Java library that caused the issue.
1. Describe exactly what went wrong (if there is an exception, please provide us the stack trace).
1. Describe exactly what you would have expected to happen.
1. And, if possible, also provide a piece of example code that triggers the issue?

This would help us tremendously to better understand what's going on and if there at all is something we should look into. I'd love to help you, but right now I'm not sure I understand what to help you with.

--László

**Comment by agung2019** [comment]
Hello Laz,

I think the latest library is better than ever :) so we can closed this
issue.

I hope Radix will be the leading solution of Distributed Ledger platform in
the future. I am currently still learning on the source code. And is very
interesting.

Here is my suggestion for future improvements:
1. Please include the protobuff for the next API version.
2. An additional async transaction will be great, if possible.
3. Also consider the smart contract.
4. An offline QR code wallet would be a challange, I guess.
5. Please also accomodate the crypto gateway service or may be ACH clearing
house function in the future.
6. In case of "currency commodity" a clear Money supply (emission?)
function might be interesting.
7. Consider to include the DAG on the API.
8. Monetary formatting function will be useful for developers.

Anyway I will inform you if I found any bugs. Many thanks for your kindly
attention.

Regards,
Agung

**Comment by laszlourszuly** [comment]
Thank you for your feedback, Agung!
