### ISSUE TITLE
Default to utf-8 encoding

### ISSUE THREAD

**Issue by nadam** [radixdlt/radixdlt-java#140]
Utf-8 is not always default in Java, so needs to be added as encoding parameter to `String.getBytes()` and `new String()` where necessary.

I've tried adding it to Data.java, TokenTransfer.java, RadixMessaging.java and RadixWallet.java, but not sure if that's enough or too much. Anyway, it works so far.

**Comment by talekhinezh** [comment]
@nadam Please check: https://github.com/radixdlt/radixdlt-java/pull/197 to see if this fixes the issue.

**Comment by MuncleUscles** [comment]
Assumed to be fixed
