### ISSUE TITLE
Client PoW Configurability

### ISSUE THREAD

**Issue by lfeagan** [radixdlt/radixdlt-java#266]
Hi,
I am trying to do some client-based benchmarking. On the server-side, I can disable PoW with "debug.nopow". However, the client has a fixed value of 16 to compute the PoW. This inherently limits a client to around 17 tps per core. I understand why this setting is here for a public network, but for benchmarking or a private network this seems unnecessary. What are your thoughts on adding configurability to disable PoW or configure the # of leading bits. Should the client inquire with the server to determine the # of required bits after connecting? If done via client config, should it be via a file similar to default.config on the server or via the BootstrapConfig-->RadixUniverseConfig class? My personal thoughts are that the client should inquire with the server as it is the server that sets and enforces the rules.
Thanks,
Lance

**Comment by talekhinezh** [comment]
We actually have plans on removing the POW fee relatively soon. If this was to be kept as a configuration parameter though, yes this information would likely be kept somewhere in the genesis atom which effectively acts as the application configuration data shared by both server and client.

**Comment by lfeagan** [comment]
Thanks for quick reply. As it sounds like you are already working address this I am going to close this issue.
