### ISSUE TITLE
Maven Dependency Incorrect

### ISSUE THREAD

**Issue by lfeagan** [radixdlt/radixdlt-java#297]
Hi,
The Gradle dependency in the README.md is incorrect. It should be
implementation 'com.github.radixdlt:radixdlt-java:1.0-beta.18'
But instead says:
implementation 'com.radixdlt:radixdlt-java:1.0-beta.18'

Which doesn't work.
Cheers!

**Comment by clstrfsck** [comment]
Hi @lfeagan 

We have custom domain name set up per jitpack documentation on [Custom Domain Name](https://jitpack.io/docs/#custom-domain-name).

You should be able to see our TXT record:
```
$ nslookup -query=TXT git.radixdlt.com jay.ns.cloudflare.com
Server:		jay.ns.cloudflare.com
Address:	173.245.59.123#53

git.radixdlt.com	text = "https://github.com/radixdlt"
```

We are using the `com.radixdlt:radixdlt-java:*` style internally with no issues.

Sometimes Jitpack takes a little time to generate artifacts for versions/tags that have not been retrieved for a while, so perhaps you are seeing timeout failures as a result of this?

**Comment by clstrfsck** [comment]
Didn't mean to close — just waiting to hear back from @lfeagan

**Comment by lfeagan** [comment]
Thanks! Not sure why it failed to work the other day, when the "regular" jitpack identifier did. But it is fine now. Cheers!

**Comment by clstrfsck** [comment]
Thanks!  Closing...
