### ISSUE TITLE
Gradle build fails due to missing bintray credentials

### ISSUE THREAD

**Issue by machisuji** [radixdlt/radixdlt-java#3]
Following the [Getting Started](https://github.com/radixdlt/radixdlt-java/wiki/get-started) guide I tried building the Radix JAR since the maven dependency doesn't seem to be working (seems empty?).
But the build fails with:

```
$ gradle build

FAILURE: Build failed with an exception.

* Where:
Build file '/home/markus/dev/radix/radixdlt-java/build.gradle' line: 94

* What went wrong:
A problem occurred evaluating root project 'radixdlt-java'.
> Could not get unknown property 'bintrayUser' for root project 'radixdlt-java' of type org.gradle.api.Project.
```

I just removed the bintray bit from the `build.gradle` to get the build running. But it would be great if new users didn't have to do that. Also the current build for 0.9.0 (current master) is failing here due to 2 failing tests.

```
> Task :radixdlt-java:test

com.radixdlt.client.wallet.TransactionAtomsTest > testConsumerBeforeConsumable FAILED
    java.lang.IllegalStateException at TransactionAtomsTest.java:46

com.radixdlt.client.wallet.TransactionAtomsTest > testConsumerWithNoConsumable FAILED
    java.lang.IllegalStateException at TransactionAtomsTest.java:28

26 tests completed, 2 failed
```

The JAR is still built but failing tests don't look good and, well, it might mean something is actually broken.

**Comment by talekhinezh** [comment]
Ack, yes thanks for catching that! Need to update the wiki as well as a lot of the stuff there is old info.

As for the failed tests, definitely weird as I can't repro it. Can you run:
```
gradle test -rerun-tasks -i
```

**Comment by machisuji** [comment]
Rerunning also fails although this time there's a more useful error message:

```
java.lang.IllegalStateException: Default Universe was not initialized via RadixUniverse.bootstrap()
        at com.radixdlt.client.core.RadixUniverse.getInstance(RadixUniverse.java:82)
        at com.radixdlt.client.wallet.TransactionAtomsTest.testConsumerWithNoConsumable(TransactionAtomsTest.java:28)
```

**Comment by blenessy** [comment]
Fixed the following in 0.9.1:

* problem with the missing bintrayUser
* empty jar

Can you guys please confirm that the artifact works ?

**Comment by machisuji** [comment]
The artifact works now, thanks!

**Comment by talekhinezh** [comment]
@machisuji Figured out the issue with the tests failing for you. Will have a fix out soon.

**Comment by machisuji** [comment]
@talekhinezh Thanks, all green now.
