### ISSUE TITLE
ChatBot example not compiling

### ISSUE THREAD

**Issue by ramka001** [radixdlt/radixdlt-java#65]
Hi,

The example provided in https://github.com/radixdlt/radixdlt-java/wiki/Chat-bot i.e. the final sample of code doesn't seem to compile. 

Could someone please recheck and update the example

**Comment by MarcRubio** [comment]
This should now be fixed.

**Comment by Dainius14** [comment]
Nothing there works anymore.

**Comment by talekhinezh** [comment]
@Dainius14 Heyo, thanks for catching! I've updated the package names which seems to be the culprit of the example not working. Let me know if you run into any more issues.

**Comment by talekhinezh** [comment]
Ah yes, that example requires an older version of the library:
```
implementation 'com.radixdlt:radixdlt-java:0.9.3'
```

Will have an updated version soon.

**Comment by Dainius14** [comment]
That's what I thought :) Great!
